#!/bin/bash
# /etc/init.d/inputs

### BEGIN INIT INFO
# Provides:          inputs 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO

case "$1" in 
    start)
        echo "Starting Inputs"
	/home/pi/midioutput/install/readbuttons.sh &
        /home/pi/midioutput/install/inputscripts/RUN.sh &
	        ;;
    stop)
        echo "Stopping Inputs"
        killall readbuttons.sh
        killall RUN.sh
        ;;
    *)
        echo "Usage: /etc/init.d/inputs start|stop"
        exit 1
        ;;
esac
