#!/bin/bash
# /etc/init.d/midiout

### BEGIN INIT INFO
# Provides:          midiout 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO

case "$1" in 
    start)
        echo "Starting Midiout"
	/home/pi/midioutput/midioutput & 
	aconnect 20 14
	aconnect 14 20
	        ;;
    stop)
        echo "Stopping Midiout"
        killall midioutput
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac
