#!/bin/bash

### BEGIN INIT INFO
# Provides:          vncserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO

case "$1" in 
    start)
        echo "Starting VNCserver on :0"
	su pi -c "vncserver :0 -geometry 1350x655"  
	        ;;
    stop)
        echo "Stopping Midiout"
        vncserver -kill :0
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac
